# Generated by Django 5.1.1 on 2024-09-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medias", "0003_alter_photo_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.URLField(),
        ),
    ]
